from llm_models import *

brand_intelligence_agent_model = sonar_reasoning_pro
creator_value_assessment_agent_model = gemini_2_0_flash
pricing_strategy_agent_model = sonar_reasoning_pro
negotiation_intelligence_agent_model = gemini_2_5_pro
proposal_email_agent_model = deepseek_r1
email_finder_agent_model = gemini_2_0_flash_lite
format_output_agent_model = gemini_2_0_flash_lite

